config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resource :comments
  end
  devise_for :users

  root to: "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@post = Post.find(params[:post_id])
		@comment = Comment.new
	end

	def create
		@post = Post.find(params[:post_id])
		@post.comments.create(params[:comment].permit(:comment))
		redirect_to post_comments_path(@post.id)
	end

	def show
		@post = Post.find(params[:post_id])
		@comments = @post.comments.all
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post].permit(:title, :url))
		@post.save
		redirect_to '/posts'
	end

	def show
		@post = Post.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def extlink(link)
		if link.include?("http://")
			puts link
		else
			link.insert(0, "http://")
			link
		end
	end
end

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :comment, "comment" %>
  <%= f.text_field :comment %>
  <%= f.submit 'Leave comment' %>
<% end %>

app/views/comments/show.html.erb
<% @comments.each do |comment| %>
  <%= comment.comment %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete%></li>
  <li><%= link_to 'Add a post', new_post_path %></li>
<% else %>
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
  <li><%= link_to 'Sign in', user_session_path %></li>
<% end %>
<% if @posts.any? %>
  <%@posts.each do |post| %>
    <%= link_to post.title, extlink(post.url) %>
    <%= link_to 'comments', new_post_comments_path(post) %>
  <% end %>
<% else %>
  <p>No posts yet</p>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit 'Create Post' %>
<% end %>

app/views/posts/show.html.erb
<%= @post.title %>